---
pool:  "ubuntu-latest"
trigger:
  - main

stages: 
  - stage: Build and Integration
    displayName: CI-petclinic
    jobs:
      - job: mvnjob
        displayName: mvnsample
        steps:
          - task: maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              jdkVersionOption: '1.17'